name: Basic CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and start containers
        run: |
          docker-compose build
          docker-compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Check if services are running
        run: |
          # Check backend health
          curl --fail http://localhost:8000/ || exit 1
          # Check frontend availability
          curl --fail -I http://localhost/ || exit 1

      - name: Stop containers
        if: always()
        run: docker-compose down